# Generated by Django 3.0.4 on 2020-04-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='id_token',
            field=models.CharField(default='sdfv', max_length=255),
            preserve_default=False,
        ),
    ]
