# Generated by Django 3.0.4 on 2020-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermodel_id_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='id_token',
            new_name='given_name',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='family_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='picture',
            field=models.URLField(blank=True, default=None),
        ),
    ]
