# Generated by Django 3.0.4 on 2020-04-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200411_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='picture',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
