# Generated by Django 3.0.4 on 2020-04-13 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200411_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('additional_info', models.TextField(null=True)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_name', models.CharField(max_length=255)),
                ('dest_name', models.CharField(max_length=255)),
                ('extra_people', models.ManyToManyField(related_name='extra', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
