# Generated by Django 3.0.4 on 2020-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200413_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
