# Generated by Django 3.0.4 on 2020-04-15 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trip_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_lat',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_lon',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='extra_people',
            field=models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_lat',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_lon',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
