# Generated by Django 3.0.4 on 2020-04-17 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200415_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='votes',
        ),
        migrations.AddField(
            model_name='trip',
            name='votes',
            field=models.ManyToManyField(null=True, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
