# Generated by Django 3.0.4 on 2020-04-17 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200417_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='votes',
        ),
        migrations.AddField(
            model_name='trip',
            name='voters',
            field=models.ManyToManyField(related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='extra_people',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
