# Generated by Django 3.0.4 on 2020-07-09 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200709_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
